apiVersion: v1
kind: Secret
metadata:
  name: event-pipeline-secrets
  namespace: event-pipeline
type: Opaque
stringData:
  DB_URL: "postgres://postgres:password@postgres:5432/analytics?sslmode=disable"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "password"
  MINIO_ACCESS_KEY: "minioadmin"
  MINIO_SECRET_KEY: "minioadmin"
