apiVersion: v1
kind: ConfigMap
metadata:
  name: event-pipeline-config
  namespace: event-pipeline
data:
  WORKER_ARCHIVE_BACKEND: "s3"
  AWS_REGION: "ap-south-1"
  S3_BUCKET: "go-event-pipeline-dev-event-archive"
