apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - path: patches/worker-deployment-s3.yaml
  - path: patches/aws-replica-tuning.yaml
  - path: patches/aws-ingress.yaml
  - path: patches/delete-app-configmap.yaml
  - path: patches/delete-app-secrets.yaml
  - path: patches/delete-worker-hpa.yaml
  - path: patches/delete-minio-deployment.yaml
  - path: patches/delete-minio-service.yaml
  - path: patches/delete-minio-pvc.yaml
  - path: patches/delete-minio-bucket-job.yaml
  - path: patches/delete-postgres-statefulset.yaml
  - path: patches/delete-postgres-service.yaml
  - path: patches/delete-redis-deployment.yaml
  - path: patches/delete-redis-service.yaml
