apiVersion: v1
kind: Service
metadata:
  name: collector-service
  namespace: event-pipeline
spec:
  selector:
    app: collector-service
  ports:
    - name: http
      port: 80
      targetPort: 3000
